# version: '3.1'

# services:
#   postgres:
#     image: postgres
#     restart: always
#     ports: 
#     - 5430:5432
#     environment:
#       POSTGRES_USER: dubciuc
#       POSTGRES_PASSWORD: dubciuc


version: '3'
services:
   backend:
      build:
         dockerfile: Dockerfile.back
      ports:
         - "3001:3001"
      container_name: project_backend

   db:
      build:
         dockerfile: Dockerfile.db
      ports:
         - "5430:5432"
      image: postgres
      restart: always
      environment:
         POSTGRES_USER: dubciuc
         POSTGRES_PASSWORD: dubciuc
      container_name: project_db
         