# Use a lightweight Node.js image
FROM node:14-alpine

# Set the working directory
WORKDIR /app/back

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application code
COPY . .

# Expose the port on which the app will run
EXPOSE 3001

# Command to run the application
CMD ["npm", "start"]
